### ISSUE TITLE
How to operate this repository?

### ISSUE THREAD

**Issue by dancesWithCycles** [entur/vehicle-map-demo#52]
Hi folks,
Thanks to the work and support in issue #45, I am able to run this repository on a local Linux host. Now, I would like move to the next stage.

I conclude from the web service that data from Norway is configured as source by default. As I am not aware of any documentation I like to ask the following questions.

* Can I configure alternative data sources? If yes, how?
* What interfaces or API's are used in this repository to interact with data providers?
* What is meant with ```buffer size``` and ```buffer time``` for the ```Live updates``` option?
* What is meant with ```sweep interval``` for the ```Other settings``` option?

Cheers!

**Comment by testower** [comment]
This project is a demonstration of an API we have that provides realtime vehicle information via SIRI-VM. You can find the backend / API project here: https://github.com/entur/vehicle-positions
